table dimCliente
	lineageTag: 0ae9d35a-c3e7-4600-9e42-15d6f35b0a41

	column customer_id
		dataType: string
		lineageTag: db308038-1031-47a5-9248-d98e6d5c51c3
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: c451f9b2-d81c-455e-b8b0-06ed2f4fdeeb
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition dimCliente = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(Web.Contents("https://raw.githubusercontent.com/deividgoulart/bi-project-olist/main/data/", [RelativePath="olist_customers_dataset.csv"]),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"customer_unique_id", "customer_zip_code_prefix", "customer_city"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

